### ISSUE TITLE
v44 warnings

### ISSUE THREAD

**Issue by Coobaha** [ELLIOTTCABLE/bs-deriving#2]
```
IGNORED: file ppx_deriving_runtime.cppo.mli under src/runtime is ignored because it can't be turned into a valid module name. The build system transforms a file name into a module name by upper-casing the first letter
IGNORED: file ppx_deriving_runtime.cppo.ml under src/runtime is ignored because it can't be turned into a valid module name. The build system transforms a file name into a module name by upper-casing the first letter
```

**Comment by ELLIOTTCABLE** [comment]
This should be fixed; let me know if you see any more issues with the v4.4 build.

**Comment by swuecho** [comment]
Thanks for the new version. I can finally upgrade to bs v5.2.1.

still have the warning. otherwise, works great!

```
> bsb -make-world

[15/15] Building src/Json.cmj
[16/16] Building src/axios.cmj
[3/3] Building bs_src/result.cmj
IGNORED: file ppx_deriving_runtime.cppo.mli under src/runtime is ignored because it can't be turned into a valid module name. The build system transforms a file name into a module name by upper-casing the first letter
IGNORED: file ppx_deriving_runtime.cppo.ml under src/runtime is ignored because it can't be turned into a valid module name. The build system transforms a file name into a module name by upper-casing the first letter
[5/5] Building src/runtime/ppx_deriving_runtime.cmj
[5/5] Building src/pbrt_bs.cmj
[5/5] Building src/jest.cmj
bsb: no work to do.
```

macOS 10.14.6 with "bs-platform": "^5.2.1".

**Comment by Coobaha** [comment]
@ELLIOTTCABLE warnings are still there, not fixed :/

**Comment by ELLIOTTCABLE** [comment]
*Actually* fixed in [v44.1.1](https://www.npmjs.com/package/bs-deriving/v/44.1.1), thanks to @Coobaha!
